const $=(q)=>document.querySelector(q), $$=(q)=>Array.from(document.querySelectorAll(q));
function jourFrancais(d){return ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'][d]}
function setTabFromHash(){const id=(location.hash||'#accueil').replace('#','');$$('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id)?.classList.add('active');$$('#nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('data-tab')===id));if(id==='lieux'&&window._map)setTimeout(()=>_map.invalidateSize(),100)}
window.addEventListener('hashchange', setTabFromHash);
document.addEventListener('DOMContentLoaded', ()=>{setTabFromHash(); $('#burger').addEventListener('click',()=>$('#nav').classList.toggle('show')); $('#tel').textContent=APP_DATA.phone; $('#wa').textContent=APP_DATA.phone; $('#wa').href='https://wa.me/'+APP_DATA.phone.replace(/\D/g,''); $('#wa2').href='https://wa.me/'+APP_DATA.phone.replace(/\D/g,''); renderPlaces(); renderMarkets(); renderFetes(); renderTrips(); renderExcursions();});
let _map,_layer; function initMap(){_map=L.map('map',{scrollWheelZoom:false}).setView([39.66,3.0],9); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(_map); _layer=L.layerGroup().addTo(_map);}
function renderPlaces(){initMap(); const box=$('#places'); box.innerHTML=''; _layer.clearLayers(); APP_DATA.places.forEach(p=>{const [title,type,pos,img,desc]=p; const card=document.createElement('div'); card.className='card'; card.innerHTML=`<img src="${img}"><div class="pad"><h3>${title}</h3><div class="badge">${pos.zone}</div><p>${desc}</p><button class="cta small">Voir sur la carte</button></div>`; box.appendChild(card); const m=L.marker([pos.lat,pos.lng]).addTo(_layer).bindPopup(`<strong>${title}</strong><br>${desc}`); card.querySelector('button').addEventListener('click',()=>{location.hash='#lieux'; setTimeout(()=>{_map.setView([pos.lat,pos.lng],12); m.openPopup();},120);});}); const input=$('#global-search'), res=$('#search-results'); input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase(); if(!q){res.innerHTML=''; return;} const items=[]; APP_DATA.places.forEach(p=>items.push({type:'Lieu',title:p[0],img:p[3]})); APP_DATA.excursions_plus.forEach(e=>items.push({type:'Excursion',title:e.titre,img:e.img})); APP_DATA.itineraires.forEach(rt=>items.push({type:'Road trip',title:rt.titre})); const list=items.filter(it=>it.title.toLowerCase().includes(q)).slice(0,12); res.innerHTML=list.map(it=>`<div class="card"><img src="${it.img||'assets/photos/Palma-de-Mallorca-et-sa-cathedrale-9.jpg'}"><div class="pad"><h3>${it.title}</h3><div class="badge">${it.type}</div></div></div>`).join('');});}
function renderMarkets(){const list=$('#markets'); const j=$('#filter-jour'), z=$('#filter-zone'), btn=$('#btn-today'); const draw=()=>{const jf=j.value, zf=z.value; const data=APP_DATA.markets.filter(m=>(jf==='Tous'||m.jour===jf)&&(zf==='Toutes'||m.zone===zf)); list.innerHTML=data.map(m=>`<div class="card"><div class="pad"><h3>${m.ville}</h3><div class="badge">${m.jour}</div><div class="badge">${m.zone}</div></div></div>`).join('');}; j.onchange=z.onchange=draw; btn.onclick=()=>{j.value=jourFrancais(new Date().getDay()); draw();}; draw();}
function renderFetes(){const c=$('#fetes-list'); c.innerHTML=APP_DATA.fetes.map(f=>`<div class="card"><div class="pad"><h3>${f.titre}</h3><div class="badge">${f.lieu}</div><p>${f.details}</p></div></div>`).join('');}
function renderTrips(){const c=$('#trips'); c.innerHTML=APP_DATA.itineraires.map(rt=>{const steps=rt.segments.map(s=>`<li><strong>${s.arret}</strong> — ${s.temps} · ${s.tips}</li>`).join(''); return `<div class="card"><div class="pad"><h3>${rt.titre}</h3><p>${rt.resume}</p><ul>${steps}</ul></div></div>`;}).join('');}
function renderExcursions(){const c=$('#exc-list'); c.innerHTML=APP_DATA.excursions_plus.map(e=>`<a class="card" href="${e.url}" target="_blank" rel="noopener"><img src="${e.img}"><div class="pad"><h3>${e.titre}</h3></div></a>`).join('');}
